language:
  node_js
node_js:
  - "node"
  - "lts/*"
install:
  - yarn
  - yarn global add codecov
script:
  - yarn test --coverage
after_success:
  - coverage
cache:
  yarn: true
  directories:
    - node_modules
